### ISSUE TITLE
Can't save objects to xero.

### ISSUE THREAD

**Issue by asavpatel92** [freakboy3742/pyxero#103]
I try to do this 

```
contacts = xero_client.contacts.all()
for contact in contacts:
    if contact.get("Name") == supplier_name:
        contact["Addresses"][0]["City"] = "Manhattan"
        xero_client.contacts.save(contact)

# HERE I am trying to mark the invoice as paid.
invoices = xero_client.invoices.get(invoice_number)
for invoice in invoices:
    if invoice.get("Contact").get("Name") == supplier_name:
        invoice["Status"] = "PAID"
        xero_client.invoices.save(invoice)        
```
but it's throwing this error in both cases.

```
  xero_client.contacts.save(contact)
  File "/Library/Python/2.7/site-packages/xero/manager.py", line 187, in wrapper
    raise XeroBadRequest(response)
  File "/Library/Python/2.7/site-packages/xero/exceptions.py", line 24, in __init__
    for elem in data['Elements']
    KeyError: 'Elements'
```

can someone please help me solve this.

**Comment by asavpatel92** [comment]
btw Library is generating following XML and it seems it's not correct:
```
<?xml version="1.0" encoding="UTF-8"?>
<Contact>
   <Addresses>
      <City>Manhattan</City>
   </Addresses>
   <HasAttachments>false</HasAttachments>
   <Phones>
      <PhoneAreaCode />
      <PhoneNumber />
      <PhoneType>DDI</PhoneType>
      <PhoneCountryCode />
      <PhoneAreaCode />
      <PhoneNumber />
      <PhoneType>DEFAULT</PhoneType>
      <PhoneCountryCode />
      <PhoneAreaCode />
      <PhoneNumber />
      <PhoneType>FAX</PhoneType>
      <PhoneCountryCode />
      <PhoneAreaCode />
      <PhoneNumber />
      <PhoneType>MOBILE</PhoneType>
      <PhoneCountryCode />
   </Phones>
   <IsSupplier>true</IsSupplier>
   <ContactGroups />
   <BankAccountDetails />
   <ContactID>06f98f7c-7878-4472-bbed-7811bf3dcb54</ContactID>
   <HasValidationErrors>False</HasValidationErrors>
   <EmailAddress />
   <ContactPersons />
   <IsCustomer>false</IsCustomer>
   <ContactStatus>ACTIVE</ContactStatus>
   <Name>asav supplier</Name>
</Contact>
```

**Comment by MJMortimer** [comment]
Hi @aidanlister,

I've just tried to replicate this issue and found that the same thing is hapening for me on the latest master. We have an open community thread disscusion here for reference https://community.xero.com/developer/discussion/12184472.

Has the serialization process been changed lately that could cause the serializtion to be incorrect?

Cheers,
Matt

**Comment by aidanlister** [comment]
No intentional changes ... I'll do some bisection and get back to you.

**Comment by aidanlister** [comment]
I added some tests to pick up on the problem:
https://github.com/freakboy3742/pyxero/commit/2ef0ce4cfa6acb28f69a0fe88036de6769022f36

**Comment by aidanlister** [comment]
There was a PR which fixed this, which is now merged in.

**Comment by MJMortimer** [comment]
@aidanlister, I've opened one last PR to help resolve Asav's issue. The PR will also help others tryig to use the Library i the same fashion. 

PR #105

**Comment by asavpatel92** [comment]
Thanks guys for all the help.
last fix solved my ```contacts.save()``` problem.
but now when I try to save invoice info the same way. I am getting this error.

```
PostDataInvalidException: The element 'IsDiscounted' was not recognised. Ensure the element name has the correct case and that there are no duplicate elements of the same name.: 
```

**Comment by asavpatel92** [comment]
Adding the following fields into ```NO_SEND_FEILDS``` fixed my issue.
I don't know if it's a correct way of solving this or not.

```
'IsDiscounted',
'DateString',
'HasErrors',
'DueDateString',
```

Please advise.

**Comment by aidanlister** [comment]
I wonder if something has changed on Xero's end to be more strict? I'll add these too.

**Comment by nadzimo** [comment]
Also getting this error when trying to update an invoice:
```PostDataInvalidException: The element 'IsDiscounted' was not recognised. Ensure the element name has the correct case and that there are no duplicate elements of the same name.:```

Any update on that old issue?

**Comment by peircej** [comment]
I had same error as @nadzimo and similar solution to previous. When I add "HasAccount" to the pyxero.basemanager.BaseManager.NO_SEND_FIELDS, that PostDataInvalidException goes away

**Comment by aidanlister** [comment]
If someone makes a PR I'll merge it

**Comment by peircej** [comment]
There's actually a further issue with (at least one of) the date fields because when the above issue was fixed the API then complained about the date being in the wrong format. Re-saving the datetime to a simple date (in my script not in pyxero) fixed that problem
