### ISSUE TITLE
PyCrypto no longer a hard requirement, please remove from setup.py

### ISSUE THREAD

**Issue by OOPMan** [freakboy3742/pyxero#112]
Hi

PyXero lists PyCrypto in the install_requires. PyCrypto is not directly used by PyXero, but is rather an extra dependency of older versions of oauthlib (https://github.com/idan/oauthlib/blob/0.3.4/setup.py) which is used by requests-oauthlib.

PyXero depends on requests-oauthlib >= 0.3.0 which in turn depends on oauthlib >= 0.3.4. The latest version of requests-oauthlib is 0.5.0 and depends on oauthlib >= 0.6.2. 

The latest version of oauthlib is 1.0.3 and includes significant changes. Significant among the changes in the 1.x.x release of oauthlib is the removal of any dependence on PyCrypto. oauthlib now uses the cryptography library to handle RSA keys and PyCrypto is no longer a requirement.

It would be great if PyCrypto could be removed from the setup.py file for PyXero as this would allow PyXero to be used with PyPy without having to manually check-out the project and patch the setup.py.

It might be best to include a note in the README stating that uses of older versions of oauthlib < 1.0.0 will need to install PyCrypto?

**Comment by aidanlister** [comment]
I'm on my phone so I can't check this but don't we do a lot more with
crypto than just the oauth? There's the private and partner keys which need
to be used to sign requests etc.

**Comment by aidanlister** [comment]
Nope it's all oAuth, you're right @OOPMan. We'll make a new release around this and document the change in the release notes.

**Comment by OOPMan** [comment]
Awesome, thanks!
