### ISSUE TITLE
PEM files for Partner Authentication 

### ISSUE THREAD

**Issue by cbalex44** [freakboy3742/pyxero#119]
I downloaded the .p12 Entrust Client SSL key for Partner Authentication. I'm a little confused about where the following files come from in the Partner Auth section of the README file

    client_cert = ('/path/to/entrust-cert.pem',                
    '/path/to/entrust-private-nopass.pem')

If I downloaded a p12 key, do I need to convert it and split into two different pem keys?

**Comment by MattHealy** [comment]
Yes, you need to split the p12 file. There are instructions listed on the developer documentation site http://developer.xero.com/documentation/getting-started/partner-applications/

**Comment by cbalex44** [comment]
Whoops. Feel free to close this issue
