### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by ccsalway** [freakboy3742/pyxero#121]
Just tried pip install pyxero (as well as git clone) but when run, I get the error:

  File "/usr/local/lib/python2.7/dist-packages/oauthlib/oauth1/rfc5849/signature.py", line 473, in _jwt_rs1_signing_algorithm
    import jwt.algorithms as jwtalgo
ImportError: No module named algorithms

These are my installed python modules:
Jinja2==2.8
MarkupSafe==0.23
MySQL-python==1.2.5
PyJWT==0.2.1
PyYAML==3.11
WebOb==1.5.1
argparse==1.2.1
bcrypt==2.0.0
cffi==1.3.0
chardet==2.3.0
colorama==0.3.2
cryptography==0.6.1
ecdsa==0.11
euca2ools==3.1.0
gcimagebundle==1.2.10
html5lib==0.999
lxml==3.4.0
oauthlib==1.0.3
paramiko==1.15.1
ply==3.4
pycparser==2.14
pycrypto==2.6.1
pylibmc==1.5.0
python-dateutil==2.4.2
pyxero==0.7.0
requestbuilder==0.2.3
requests==2.4.3
requests-oauthlib==0.6.0
simplejson==3.8.1
six==1.8.0
uWSGI==2.0.11.2
urllib3==1.9.1
uwsgitop==0.9
webapp2==2.5.2
wheel==0.24.0
wsgiref==0.1.2

**Comment by zerc** [comment]
Try to update the PyJWT. I use `PyJWT==1.4.0` and `algorithms` module exists.

**Comment by aidanlister** [comment]
I'll add it explicitly
