### ISSUE TITLE
Retrieve banktransactions by date range

### ISSUE THREAD

**Issue by hoandang** [freakboy3742/pyxero#124]
Hi, just a very quick question.

According to Xero API, we can retrieve data between a date range http://developer.xero.com/documentation/getting-started/http-requests-and-responses/#title4, so I am wondering how I achieve this request with pyxero?

Thanks heaps

**Comment by aidanlister** [comment]
See the examples in README, eg xero.contacts.filter(since=datetime(2013, 1, 1))

**Comment by hoandang** [comment]
Hi, correct me if I am wrong, but the example just queries the data since the given date up to today. I am still curious on how to send a request like 

    xero.contacts.filter(from=date(2014,6,30), to=date(2015,7,1))

Thanks

**Comment by aidanlister** [comment]
Can you try something like:

xero.contacts.filter(raw='Date >= DateTime(2015, 01, 01) && Date < DateTime(2015, 12, 31)')

**Comment by abismail** [comment]
This issue should be reopened; I've used the above example and it just doesn't work, I'm getting absolutely nothing back when I query like this;

```
reports = xero.invoices.filter( raw='Date>=DateTime(2017-12-01) && Date<=DateTime(2018-02-28)' )
print reports
```

but when I do this; 
```
reports = xero.invoices.filter( since = datetime( 2018, 2, 1 ), page=1 )
```

then I get a lot of them, but without the invoices that do not have any lineitems > which is the issue that I'm trying to solve right now.
