### ISSUE TITLE
Do not understand how to add contacts to contact groups.

### ISSUE THREAD

**Issue by Jafula** [freakboy3742/pyxero#132]
http://developer.xero.com/documentation/api/contactgroups/#PUT

"To add contacts to a contact group use the following url /ContactGroups/ContactGroupID/Contacts"

According to the documentation I can put contacts in a contact group, but I have no idea how to actually do this using PyXero. Has anyone tried to do this?

The Xero API previewer also seems to have this limitation.

**Comment by aidanlister** [comment]
See https://github.com/freakboy3742/pyxero/issues/107
