### ISSUE TITLE
all() only returns 100 results for purchaseorders

### ISSUE THREAD

**Issue by svenhuster** [freakboy3742/pyxero#133]
xero.purchaseorders.all() does only return 100 results rather than all as suggested in the documentation.

Iterating though all paginated results via filter(page=...) works to retrieve all results. 

```
credentials = PrivateCredentials('...', ra_key)
xero = Xero(credentials)
xero.purchaseorders.all()
```

**Comment by schinckel** [comment]
Originally the APIs were not paginated. Payroll was the first, I think they all may be now.

**Comment by Munduruca** [comment]
@svenhuster @schinckel I'm experiencing the same when I try to get "journals". Would you guys have any workaround for that?

I tried .filter(since=) and .filter(page=<number>)

Cheers
