### ISSUE TITLE
pyxero cannot convert invoice with several line items from dictionary to XML

### ISSUE THREAD

**Issue by SimonSchwendner** [freakboy3742/pyxero#136]
Hi all,

I am trying to use the wrapper class to create an invoice with several line items. The problem is that the dictionary below is being converted into an XML that ignores the fact that there are TWO line items. 

In particular, I mean that I want to see <LineItem>ABC</LineItem><LineItem>DEF</LineItem> but for some reason pyxero mashes it together to just be  <LineItem>ABCDEF</LineItem>.

How can I get around this issue? Do I need to make different dictionaries? How would I achieve this?

DICTIONARY:
{
   "Contact": {
      "Name": "Cool Cars"
   },
   "Date": "somedate",  <- IGNORE THIS
   "DueDate": "somedate",  <- IGNORE THIS
   "LineAmountTypes": "Exclusive",
   "LineItems": {
     "LineItem": [
         {
            "AccountCode": "4000",
            "Description": "LINE1",
            "Quantity": 50,
            "TaxAmount": 6250,
            "UnitAmount": 1000
         },
         {
            "AccountCode": "1530",
            "Description": "LINE2",
            "Quantity": 50,
            "TaxAmount": 62.5,
            "UnitAmount": 10
         }
      ]
   },
   "Status": "AUTHORISED",
   "Type": "ACCREC"
}

XML:
`
<Invoice>
    <Status>AUTHORISED</Status>
    <Contact>
        <Name>Cool Cars</Name>
    </Contact>
    <Date>2016-04-06T00:00:00</Date>
    <LineAmountTypes>Exclusive</LineAmountTypes>
    <LineItems>
          <LineItem>
            <AccountCode>4000</AccountCode>
            <TaxAmount>6250.0</TaxAmount>
            <UnitAmount>1000</UnitAmount>
            <Description>LINE1</Description>
            <Quantity>50</Quantity>
            <AccountCode>1530</AccountCode>
            <TaxAmount>62.5</TaxAmount>
            <UnitAmount>10</UnitAmount>
            <Description>LINE2</Description>
            <Quantity>50</Quantity>
        </LineItem>
    </LineItems>
    <Type>ACCREC</Type>
    <DueDate>2016-04-07T00:00:00</DueDate>
</Invoice>
`

**Comment by SimonSchwendner** [comment]
SOLVED. 

There is this weird function called "isplural" in the basemanager.py script which essentially decides to create the desired XML nodes but only it the list is located at "LineItems" and not at "LineItem".

**Comment by smizon** [comment]
Hello SimonSchwendner, 

I currently have the same issue, it works for 1 LineItem and breaks if it has more.

how did you go about solving this?
