### ISSUE TITLE
Cannot unserialize xero response

### ISSUE THREAD

**Issue by rrggrr** [freakboy3742/pyxero#147]
### Environment:

OSX - Python 3.5.1 - Anaconda
PATH: /Users/debbie/anaconda3/bin/python
OpenSSL Version: 1.0.2h-0 (Also fails under 1.0.2g)
_(Additional environment data at end of issue)_
### Test code:

```
from xero import Xero
from xero.auth import PrivateCredentials
with open("/./Users/<redacted>/<redacted>/publickey.cer") as keyfile:
  rsa_key = keyfile.read()
credentials = PrivateCredentials("<redacted>", rsa_key)
xero = Xero(credentials)
xero.contacts.all()
```
### Error message:

> Traceback (most recent call last):
>   File "xeroTest.py", line 13, in <module>
>     xero.contacts.all()
>   File "/Users/debbie/anaconda3/lib/python3.5/site-packages/pyxero-0.8.0-py3.5.egg/xero/basemanager.py", line 185, in wrapper
>   File "/Users/debbie/anaconda3/lib/python3.5/site-packages/requests/api.py", line 67, in get
>     return request('get', url, params=params, *_kwargs)
>   File "/Users/debbie/anaconda3/lib/python3.5/site-packages/requests/api.py", line 53, in request
>     return session.request(method=method, url=url, *_kwargs)
>   File "/Users/debbie/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 454, in request
>     prep = self.prepare_request(req)
>   File "/Users/debbie/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 388, in prepare_request
>     hooks=merge_hooks(request.hooks, self.hooks),
>   File "/Users/debbie/anaconda3/lib/python3.5/site-packages/requests/models.py", line 297, in prepare
>     self.prepare_auth(auth, url)
>   File "/Users/debbie/anaconda3/lib/python3.5/site-packages/requests/models.py", line 490, in prepare_auth
>     r = auth(self)
>   File "/Users/debbie/anaconda3/lib/python3.5/site-packages/requests_oauthlib-0.6.1-py3.5.egg/requests_oauthlib/oauth1_auth.py", line 88, in **call**
>     unicode(r.url), unicode(r.method), None, r.headers)
>   File "/Users/debbie/anaconda3/lib/python3.5/site-packages/oauthlib-1.1.1-py3.5.egg/oauthlib/oauth1/rfc5849/**init**.py", line 313, in sign
>   File "/Users/debbie/anaconda3/lib/python3.5/site-packages/oauthlib-1.1.1-py3.5.egg/oauthlib/oauth1/rfc5849/**init**.py", line 150, in get_oauth_signature
>   File "/Users/debbie/anaconda3/lib/python3.5/site-packages/oauthlib-1.1.1-py3.5.egg/oauthlib/oauth1/rfc5849/signature.py", line 505, in sign_rsa_sha1_with_client
>   File "/Users/debbie/anaconda3/lib/python3.5/site-packages/oauthlib-1.1.1-py3.5.egg/oauthlib/oauth1/rfc5849/signature.py", line 497, in sign_rsa_sha1
>   File "/Users/debbie/anaconda3/lib/python3.5/site-packages/oauthlib-1.1.1-py3.5.egg/oauthlib/oauth1/rfc5849/signature.py", line 574, in _prepare_key_plus
>   File "/Users/debbie/anaconda3/lib/python3.5/site-packages/PyJWT-1.4.0-py3.5.egg/jwt/algorithms.py", line 169, in prepare_key
>   File "/Users/debbie/anaconda3/lib/python3.5/site-packages/cryptography-1.3.1-py3.5-macosx-10.5-x86_64.egg/cryptography/hazmat/primitives/serialization.py", line 24, in load_pem_public_key
>     return backend.load_pem_public_key(data)
>   File "/Users/debbie/anaconda3/lib/python3.5/site-packages/cryptography-1.3.1-py3.5-macosx-10.5-x86_64.egg/cryptography/hazmat/backends/multibackend.py", line 298, in load_pem_public_key
>     return b.load_pem_public_key(data)
>   File "/Users/debbie/anaconda3/lib/python3.5/site-packages/cryptography-1.3.1-py3.5-macosx-10.5-x86_64.egg/cryptography/hazmat/backends/openssl/backend.py", line 1095, in load_pem_public_key
>     self._handle_key_loading_error()
>   File "/Users/debbie/anaconda3/lib/python3.5/site-packages/cryptography-1.3.1-py3.5-macosx-10.5-x86_64.egg/cryptography/hazmat/backends/openssl/backend.py", line 1337, in _handle_key_loading_error
>     raise ValueError("Could not unserialize key data.")
> ValueError: Could not unserialize key data.

**Comment by rrggrr** [comment]
UPDATE1 - command below may resolve this error, but another emerges in its place:
`DYLD_LIBRARY_PATH=/usr/local/opt/openssl/lib`

   **return b.load_pem_public_key(data)
  File "/Users/debbie/anaconda3/lib/python3.5/site-packages/cryptography-1.3.1-py3.5-macosx-10.5-x86_64.egg/cryptography/hazmat/backends/openssl/backend.py", line 1095, in load_pem_public_key
    self._handle_key_loading_error()
  File "/Users/debbie/anaconda3/lib/python3.5/site-packages/cryptography-1.3.1-py3.5-macosx-10.5-x86_64.egg/cryptography/hazmat/backends/openssl/backend.py", line 1337, in _handle_key_loading_error
    raise ValueError("Could not unserialize key data.")
ValueError: Could not unserialize key data.**

**Comment by rrggrr** [comment]
Possibly related to openssl access issues on OSX El Capitan:
https://github.com/caktus/developer-documentation/issues/25
https://github.com/pyca/cryptography/issues/2138

**Comment by rrggrr** [comment]
RESOLVED: Error was supplying the public instead of private key for unserializing the response. That said, the openssl issues on El Capitan were real and required time to resolve.

**Comment by romgar** [comment]
@aidanlister this issue can be closed :+1:
