### ISSUE TITLE
Creating MultiLine Items with Invoices

### ISSUE THREAD

**Issue by smizon** [freakboy3742/pyxero#156]
Hi everyone,

I currently have an issue with creating invoices with more than 1 LineItem.
Using: python3.5,  on centos7
           pyxero - version: 0.8.0

data Object sent to pyxero

> {'Contact': 
> {'Name': '1609-07000'},
> 'Type': 'ACCREC', 
> 'Status': 'AUTHORISED', 
> 'LineAmountTypes': 'Inclusive', 
> 'Date': datetime.datetime(2016, 10, 4, 13, 49, 8, 568539), 
> 'Reference': 'XS 123 123 Manchester - Stephen Mizon CCARDNone', 
> 'DueDate': datetime.datetime(2016, 10, 4, 13, 49, 8, 568539), 
> 'LineItems': 
>   {'LineItem': [
>               {'Quantity': '1', 
>       'Description': 'PS Revision - Discount: 0%', 
>       'AccountCode': '211', 
>       'UnitAmount': '50', 
>       'Tracking': {'TrackingCategory': 
>                       {'Option': 'Manchester', 'Name': 'Department'}
>                   }, 
>       'LineAmount': '50'},
> 
> ```
>   {'Quantity': '1', 
>   'Description': 'PS Revision - Discount: 0%', 
>   'AccountCode': '211', 
>   'UnitAmount': '50', 
>   'Tracking': {'TrackingCategory': 
>                   {'Option': 'Manchester', 'Name': 'Department'}
>               }, 
>   'LineAmount': '50'},
> ```
> 
>   ]}}

Response Message produces:
_PostDataInvalidException: The element 'Quantity' was not recognised. Ensure the element name has the correct case and that there are no duplicate elements of the same name._

however if there is one LineItem sent it works.

I think it could be related to how the XML is generated. However not sure how i can resolve this

**Comment by smizon** [comment]
Hello Again,

I have solved this issue, 

> 'LineItems': 
> {'LineItem': [  <-------- Removed 
> {'Quantity': '1

Just needed to remove LineItem tag

**Comment by romgar** [comment]
@aidanlister this issue can be closed 👍
