### ISSUE TITLE
New release of pyxero on PyPi

### ISSUE THREAD

**Issue by romgar** [freakboy3742/pyxero#176]
Hi @aidanlister, 

I think that, related to the number of fixes / new functionalities, we could release a new version of `pyxero`.
What do you think?

**Comment by romgar** [comment]
@aidanlister did you have time to think about this?

**Comment by aidanlister** [comment]
Hey that sounds good, do you need me to do it?

**Comment by romgar** [comment]
AFAIK, we need to be owner or maintainer on PyPi for that.

**Comment by freakboy3742** [comment]
@aidanlister If the time has come for a new release, let me know and I'll roll one.

**Comment by aidanlister** [comment]
@freakboy3742 great, @romgar ready when you are

**Comment by lvieirajr** [comment]
Any timeframe on this?
It would be great to get a newer version from pypi, specially with the new entrusr certificate deprecation from #184.

**Comment by lvieirajr** [comment]
@romgar Thank you, I'm excited for this upcoming release.

**Comment by SableWalnut** [comment]
👍

**Comment by romgar** [comment]
@aidanlister tested on production, seems completely fine! Let's release it!

**Comment by aidanlister** [comment]
Okay great, I'll roll, would you be able to suggest a changelog?

**Comment by romgar** [comment]
@aidanlister I have initiated a ChangeLog file some time ago (https://github.com/freakboy3742/pyxero/blob/master/ChangeLog.rst). Did you have something else in mind?

**Comment by aidanlister** [comment]
@romgar super star, thanks.

https://github.com/freakboy3742/pyxero/releases/tag/v0.9.0

If there's no issues over the next few days, @freakboy3742 will get you to push it up.

**Comment by romgar** [comment]
@aidanlister probably not a lot of people tried the tagged version. I didn't encounter any issue on my side with `0.9`. Let's release it.

**Comment by freakboy3742** [comment]
I've just pushed a 0.9.0 release to PyPI. Thanks to everyone for the great work!
