### ISSUE TITLE
Cryptography requirement too strong?

### ISSUE THREAD

**Issue by jneves** [freakboy3742/pyxero#177]
I have 2 packages that are requiring cryptography, one with a restriction of >=1.7.1 and current pyxero master at ==1.3.1. This fails. As I was using pyxero with 1.7.1 before, I'd like to ask if the restriction has a reason other than making sure the package is there. If not, I can submit a patch for cryptography>=1.3.1.

**Comment by romgar** [comment]
I'm +1 for this change, as I had the exact same issue in one of my projects.

@aidanlister, any reason to have an explicit version pinned? I saw https://github.com/freakboy3742/pyxero/commit/35f32d8d5313aca7445d55bf5c3bb415c01a0150 referring #90 and #91 related to this pinning.

**Comment by aidanlister** [comment]
That's right, I pinned it to resolve module import bugs that were popping up. I'm happy to remove it now, I'm sure the issue has been resolved in the other package.
