### ISSUE TITLE
Is AccountNumber__contains a valid filter?

### ISSUE THREAD

**Issue by rich-lloyd-judd** [freakboy3742/pyxero#181]
Trying to retrieve a contact using a contains filter on AccountNumber throws an UnhandledExceptionError

`{
  "ErrorNumber": 500,
  "Type": "UnknownErrorException",
  "Message": "An error occurred in Xero. Check the API Status page http://status.developer.xero.com for current service status. Contact the API support team at api@xero.com for more assistance."
}`

Is this a valid call or does __contains only work on Name?

`xero_contact = xero.contacts.filter(AccountNumber__contains=ks_number)`

**Comment by romgar** [comment]
Hi @rich-lloyd-judd !

It seems that some fields support this `contains` (`Name`, `EmailAddress`, ...) but not other ones (`AccountNumber`, `FirstName`, `LastName`, ...).
It would be worth to ask Xero about it.

**Comment by MJMortimer** [comment]
Hey @rich-lloyd-judd,

The issue is that your filter is on an option contact property. 

If you try filter based on an optional property and a single contact does not have it, you will recieve that error. Your filter needs to include a check for the AccountNumber property not being null

**Comment by rich-lloyd-judd** [comment]
Thanks @romgar @MJMortimer that's solved it. Xero confirmed that was the problem too.

This worked for me

`raw_contact_filter = 'AccountNumber!=null&&AccountNumber.contains("' + ks_number + '")'
 xero_contact = xero.contacts.filter(raw=raw_contact_filter)`
