### ISSUE TITLE
Entrust certificate deprecation

### ISSUE THREAD

**Issue by aidanlister** [freakboy3742/pyxero#183]
From Xero:
Important: Starting Jan 1, 2017, we began deprecating support for 2-way SSL for Partner Apps. Please reply to this email and confirm you've received this important information.
 
With this change, you no longer need an Entrust certificate, and you’ll need to update your integration to reference api.xero.com as opposed to api-partner.xero.com.  You can find the most current information in our Developer Center which I have linked to below:
 
Xero Developer Center: Entrust Certificate Deprecation
https://developer.xero.com/documentation/auth-and-limits/entrust-certificate-deprecation

I think we should be safe to change XERO_PARTNER_BASE_URL here,
https://github.com/freakboy3742/pyxero/blob/master/xero/constants.py

And then just drop the parameters here,
https://github.com/freakboy3742/pyxero/blob/master/xero/auth.py#L320

(migration route already documented here: https://developer.xero.com/documentation/auth-and-limits/entrust-certificate-deprecation at the bottom)

Anyone have time to work on this?

**Comment by MattHealy** [comment]
Some of this was started in https://github.com/freakboy3742/pyxero/pull/168 but I'm happy to finish it off. I assume we don't have to worry about retaining any references to `client_cert` for backwards compatibility?

**Comment by MattHealy** [comment]
I've committed some changes here https://github.com/MattHealy/pyxero/tree/entrust but I want to do a real test on the Xero API before submitting a PR.

**Comment by MattHealy** [comment]
Real tests worked fine. PR #184 created

**Comment by romgar** [comment]
Closed by #184 merge.
