### ISSUE TITLE
How to add LinkedTransactions?

### ISSUE THREAD

**Issue by subodh-malgonde** [freakboy3742/pyxero#193]
`LinkedTransactions` is not available in the list of objects for Xero, I am using this workaround:

```
from xero.manager import Manager
api_obj = Xero(creds, user_agent='my_user_agent')

object_name = 'LinkedTransactions'
setattr(api_obj, object_name.lower(), Manager(object_name, credentials=creds, user_agent='my_user_agent'))
```

After this I am able to use methods like `api_obj.linkedtransactions.filter` and `api_obj.linkedtransactions.all`, but I am unable to create new transactions. When I call the following:

     api_obj.linkedtransactions.put(linked_transactions)

I get a `[None]` response. It does not throw an error and the `LinkedTransaction` objects is not created. Can someone help?

**Comment by subodh-malgonde** [comment]
We found a workaround:

    with open('xero-cert/privatekey.pem') as keyfile:
            rsa_key = keyfile.read()
    
    state = {
        'oauth_token': oauth_token, 'oauth_token_secret': oauth_token_secret, 
        'oauth_authorization_expires_at': self.oauth_authorization_expires_at.replace(tzinfo=None), 
        'verified': self.verified, 'oauth_expires_at': self.oauth_expires_at.replace(tzinfo=None), 
        'consumer_key': XERO_CONSUMER_KEY, 'consumer_secret': XERO_CONSUMER_SECRET, 
        'callback_uri': XERO_REDIRECT_URL, 'oauth_session_handle': oauth_session_handle
    }
    
    state['rsa_key'] = rsa_key
    creds = PartnerCredentials(**state)
    if creds.expired():
        creds.refresh()
    xml_body = "<LinkedTransaction><SourceTransactionID>%s</SourceTransactionID><SourceLineItemID>%s</SourceLineItemID>" \
                "<ContactID>%s</ContactID></LinkedTransaction>" % (InvoiceID,LineItemID, customer_contact_id)
    params = {'oauth_session_handle': creds.state['oauth_session_handle']}
    headers = {'User-Agent': 'expensetron'}
    response = requests.post(url='https://api.xero.com/api.xro/2.0/LinkedTransactions', params=params, headers=headers, auth=creds.oauth, data=xml_body)

Not sure why the earlier method did not work.

**Comment by cjw296** [comment]
@freakboy3742 - it does look like [this endpoint](https://developer.xero.com/documentation/api/accounting/linkedtransactions) is missing, so I guess this issue should be reopened?

**Comment by freakboy3742** [comment]
@cjw296 This was self-closed by the reporter, and framed more as a question than a bug/feature request. If there's something missing here (and it looks like it might be), feel free to open a new ticket framing it as a feature request.
