### ISSUE TITLE
Any field ending in "id" is incorrectly treated as a GUID field when used in a filter

### ISSUE THREAD

**Issue by NickMolloy** [freakboy3742/pyxero#200]
For instance, the 'AmountPaid' field on invoices is incorrectly treated as an ID field:

```
>>> xero.invoices.filter(AmountPaid=0.0)                                                                           
Traceback (most recent call last):                       
  File "<stdin>", line 1, in <module>                    
  File "xero/basemanager.py", line 204, in wrapper       
    raise XeroBadRequest(response)                       
xero.exceptions.XeroBadRequest: QueryParseException: Operator '==' incompatible with operand types 'Decimal?' and 'Guid'
```

This is because a filter key is considered a GUID type if it ends with "id" as can be seen [here](https://github.com/freakboy3742/pyxero/blob/2ef5e35c0bb3c39977d9eccb79aba8ce41179f1a/xero/basemanager.py#L312).

**Comment by MattHealy** [comment]
The solution could be as simple as changing

`if last_key.upper().endswith('ID'):
`

to 

`if last_key.endswith('ID'):
`

I don't think there are any data attributes that end with "ID" that aren't GUID types, and similarly data attributes ending with "id" or "Id" that are GUID types. The only ones I could find are FolderId/FileId in the Files API but that section of code doesn't use the `_filter` function from BaseManager.
