### ISSUE TITLE
Dependency PyJWT is pinned to an insecure version 1.4

### ISSUE THREAD

**Issue by fyber** [freakboy3742/pyxero#206]
In [`setup.py`](https://github.com/freakboy3742/pyxero/blob/v0.9.0/setup.py#L33) file dependency `PyJWT` is pinned to version 1.4, which is insecure according to [safety](https://github.com/pyupio/safety) tool.
The description of vulnerability is as follows:
> In PyJWT 1.5.0 and below the `invalid_strings` check in `HMACAlgorithm.prepare_key` does not account for all PEM encoded public keys. Specifically, the PKCS1 PEM encoded format would be allowed because it is prefaced with the string `-----BEGIN RSA PUBLIC KEY-----` which is not accounted for. This enables symmetric/asymmetric key confusion attacks against users using the PKCS1 PEM encoded public keys, which would allow an attacker to craft JWTs from scratch.

Is there really a need to pin ` PyJWT` to version `1.4`?
I can craft a PR to unpin this req.

**Comment by freakboy3742** [comment]
I'm not aware of a specific reason why PyJWT would need to be pinned; as long as v1.5 hasn't introduced any API changes and PyXero's tests still pass, feel free to submit a PR.

**Comment by Skyross** [comment]
@freakboy3742 Here is the related PR (https://github.com/freakboy3742/pyxero/pull/207).

**Comment by Skyross** [comment]
Hi! @freakboy3742 have any updates on this issue?

**Comment by jneves** [comment]
Just hit this. Checked that the tests in the PR failed because of an error on env setup. Any reason this is not merged yet?

**Comment by jroblak** [comment]
Running into this as well. Any idea on timelines for merging this PR?
