### ISSUE TITLE
Can't delete payment - 'Manager' object has no attribute 'post'

### ISSUE THREAD

**Issue by lifeofdave** [freakboy3742/pyxero#209]
The docs say that to delete a payment one should do a `POST https://api.xero.com/api.xro/2.0/Payments/b26fd49a-cbae-470a-a8f8-bcbc119e0379`
However the Xero API python wrapper doesn't support a POST and returns `AttributeError: 'Manager' object has no attribute 'post'`
Is there a way to hack this together so delete payment can be achieved via the wrapper?

**Comment by timrichardson** [comment]
why was this closed? How do we delete a payment? the .delete method does a DELETE request, which is no good.

**Comment by timrichardson** [comment]
I don't see this documented anywhere. Here is how to delete a payment. 
Make a dict with only two elements and save it, example: 

```
 payment_to_be_deleted = {"PaymentID": p["PaymentID"]}
 payment_to_be_deleted["Status"] = "DELETED"
 xero.payments.save(payment_to_be_deleted)
```
