### ISSUE TITLE
PyJWT throws deprecation errors

### ISSUE THREAD

**Issue by sminnee** [freakboy3742/pyxero#231]
Use of this module throws the following warning:

```
.../lib/python3.5/site-packages/jwt/algorithms.py:178: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
```

This has been fixed in https://github.com/jpadilla/pyjwt/releases/tag/1.5.3

Recommend setting the minimum version of pyjwt to 1.5.3.

**Comment by assembledadam** [comment]
+1

**Comment by cas--** [comment]
Could we please get the pyjwt version bump with a pyxero pypi release to fix this?

**Comment by lwm** [comment]
Also seeing this, would be great to get the bump!

**Comment by schinckel** [comment]
I believe the most recent version fixes this.
