### ISSUE TITLE
Credit Note update adds 'ID' that is not recognised

### ISSUE THREAD

**Issue by benlongmire** [freakboy3742/pyxero#236]
I was trying to update the status of a credit note, and it seems that 'ID' was added to the JSON and the Xero API was saying that element is invalid when saving the change. I have since done a hack by removing the 'ID' key from the dictionary before saving.

**Running this:**
credit_note['Status'] = "VOIDED"
xero.creditnotes.save(credit_note)

**Results in this:**
PostDataInvalidException: The element 'ID' was not recognised. Ensure the element name has the correct case and that there are no duplicate elements of the same name.

**Comment by MattHealy** [comment]
Are you able to show a bit more of the code (or a simple test case) to reproduce this problem? I've glanced through the codebase and I can't see where an "ID" element would be added to the dictionary, nor should it be returned from Xero in the API response.
