### ISSUE TITLE
How does one query multiple statuses on the Invoice end point?

### ISSUE THREAD

**Issue by rhelms** [freakboy3742/pyxero#238]
The Invoices endpoint support some special arguments to facilitate multiple values for fields such as IDs, InvoiceNumbers, ContactIDs, Statuses.

The filter() function cannot seem to handle Statuses='AUTHORISED,PAID', Status__in=['AUTHORISED','PAID'] or even raw='Statuses=AUTHORISED,PAID' to make use of these optional GET parameters.

**Comment by rhelms** [comment]
Figured it out.  I needed to grab the manager, and use the extra_params property to set the extra parameter, then call filter() to do the rest of the filter.

```
invoice_manager = xero.invoices
invoice_manager.extra_params['Statuses'] = 'AUTHORISED,PAID'
invoices = invoice_manager.filter(Contact_ContactID=contact_id, Date__gte=from_date, Date__lte=to_date)
```

**Comment by jamalex** [comment]
This isn't working for me. When I add the extra_params like this, I get an empty list of results (even when there should be matches).
