### ISSUE TITLE
Payroll API is missing Superfunds

### ISSUE THREAD

**Issue by btaylor-ihr** [freakboy3742/pyxero#244]
Heya. I want to be able to fetch the superfunds out of the organisation, but I can't do that. Looks like the payroll api doesn't have support for it.

The API Previewer has this for the URL - `https://api.xero.com/payroll.xro/1.0/Superfunds`, but `api.py` only has the following

```
class Payroll(object):
    """An ORM-like interface to the Xero Payroll API"""

    OBJECT_LIST = (
        "Employees",
        "Timesheets",
        "PayItems",
        "PayRuns",
        "PayrollCalendars",
        "Payslip",
        "LeaveApplications",
    )
```

**Comment by btaylor-ihr** [comment]
I've just added `sed -i 's/"Superfunds"/"Superfunds",\n\t"Timesheets"/g' build/xero/api.py` to my pipeline as it looks like PRs are rarely approved, and I don't see the benefit in forking

**Comment by direvus** [comment]
@btaylor-ihr For what it's worth, my PR to fix this issue has just been merged.
