### ISSUE TITLE
How do I filter invoices , contacts and requesting multiple IDs at once?

### ISSUE THREAD

**Issue by whitehawk0011** [freakboy3742/pyxero#252]
for example,

        s =[]
        s.append('14aa8bd8-7473-42c7-b8bc-ca83d7a75236')
        s.append('fee88eea-f2aa-4a71-a372-33d6d83d3c45')

suppose s is my list of contacts/invoice Ids, how do I filter (i want to do something like 
xero.invoices.filter(InvoiceID__in=s)

Is it possible?

**Comment by IdlePhysicist** [comment]
I have not tried it, but according to the Xero docs for Invoices GET (under Optional parameters), it says that you can pass a comma separated string of invoice ids.

```python 
s = '14aa8bd8-7473-42c7-b8bc-ca83d7a75236,fee88eea-f2aa-4a71-a372-33d6d83d3c45'
xero.invoices.filter(InvoiceID=s)
```

Perhaps something like that might work.

**Comment by evrimoztamur** [comment]
The Xero API documentation says that filtering on IDs is a little slow, so what I do is:
```python
xero.invoices.get("?IDs={}&page=1".format(",".join(invoice_ids)))
```

**Comment by whitehawk0011** [comment]
@evrimoztamur  It worked for invoices but not for payments, Any idea how to do it on payments?

**Comment by whitehawk0011** [comment]
Solved , so closed
