### ISSUE TITLE
POSTing invoices and LineItem ordering

### ISSUE THREAD

**Issue by IdlePhysicist** [freakboy3742/pyxero#255]
Hi guys,

I am a bit stuck here, I am having issues with batch uploading to Xero. 

Some batches fail due to this error `PostDataInvalidException: Input string was not in a correct format.` This leads me to the question could newline characters (`\n`) in invoice descriptions cause the `PostDataInvalidExceptionPostDataInvalidException` ?

Another issue I am seeing is that `LineItem` order is not maintained when using the invoice.save() method. I am purposely ordering LineItems in a specific order as per my company's request. 
I am dumping/logging out both the Python dict structure and the XML (from `invoices._prepare_data_for_save()` ), and in both cases the desired order is seen.

But when I log into the Xero website, or when I look at the response from `invoices.save()` the desired order is lost. Is this a PyXero issue or rather a Xero issue ?

Many thanks

**Comment by IdlePhysicist** [comment]
The Xero support team got back to me in the end. Thanks anyway folks.

**Comment by adnan-alam** [comment]
I'm also getting this error **xero.exceptions.XeroBadRequest: PostDataInvalidException: Input string was not in a correct format**

This is the payload I'm sending but failed to create invoice.
`
{"Type": "ACCREC", "Contact": {"ContactID": "6f5cc7e34a114ed3ac053c8eb84b75c4"}, "Date": datetime.date(2023, 2, 16), "DueDate": datetime.date(2023, 2, 16), "InvoiceNumber": "INV-8", "Reference": "Adnan Alam", "CurrencyCode": "NZD", "Status": "AUTHORISED", "LineAmountTypes": "Exclusive", "LineItems": [{"Description": "Brake Pad", "Quantity": "1", "UnitAmount": "150.0", "TaxAmount": "22.5", "AccountCode": "301"}, {"Description": "adnan.alamcu", "Quantity": "00:30:00", "UnitAmount": "125.0", "TaxAmount": "0.0", "AccountCode": "302"}]}
`

XML sent by pyxero is:
`
<Invoice>
	<Type>ACCREC</Type>
	<Contact>
		<ContactID>6f5cc7e34a114ed3ac053c8eb84b75c4</ContactID>
	</Contact>
	<Date>2023-02-16T00:00:00</Date>
	<DueDate>2023-02-16T00:00:00</DueDate>
	<InvoiceNumber>INV-8</InvoiceNumber>
	<Reference>Adnan Alam</Reference>
	<CurrencyCode>NZD</CurrencyCode>
	<Status>AUTHORISED</Status>
	<LineAmountTypes>Exclusive</LineAmountTypes>
	<LineItems>
		<LineItem>
			<Description>Brake Pad</Description>
			<Quantity>1</Quantity>
			<UnitAmount>150.0</UnitAmount>
			<TaxAmount>22.5</TaxAmount>
			<AccountCode>301</AccountCode>
		</LineItem>
		<LineItem>
			<Description>adnan.alamcu</Description>
			<Quantity>00:30:00</Quantity>
			<UnitAmount>125.0</UnitAmount>
			<TaxAmount>0.0</TaxAmount>
			<AccountCode>302</AccountCode>
		</LineItem>
	</LineItems>
</Invoice>
`




I can't figure out the error, please help me on this.
