### ISSUE TITLE
Latest pyxero not on pypi (problem with put_attachment)

### ISSUE THREAD

**Issue by nadzimo** [freakboy3742/pyxero#258]
I noticed when running `pip install pyxero` it's not getting the latest code. The latest stated version on PyPi is 0.9.1 released August 27, 2018 but upon installing with pip the code for the `put_attachment` method is still missing this updated code to return the response:  
https://github.com/freakboy3742/pyxero/commit/2afeba650f7dbd484325c9f23274c1ff9e87ff6e  
How to get the latest code with pip?

**Comment by freakboy3742** [comment]
Option 1: you wait until a version is published to PyPI. I can't provide any schedule for that - it will happen when I get some spare time to do what is needed to cut a release.

Option 2: You can pass a github link to `pip install` to install the most recent modifications of a repository; you can even pin to a specific hash. For example:
```
 $ pip install git+git://github.com/freakboy3742/pyxero.git@5566f17 
```
would install the most recent code as of right now.

That same link can also be used in a requirements.txt file:
```
-e git+git://github.com/freakboy3742/pyxero.git@5566f17#egg=pyxero
```
