### ISSUE TITLE
No invoice lines using all()

### ISSUE THREAD

**Issue by ellbristow** [freakboy3742/pyxero#288]
When grabbing all invoices using invoices.all() I am not receiving any invoice lines.

![invoice_lines](https://user-images.githubusercontent.com/1309054/77150204-a5a4d000-6a93-11ea-8b95-a618c170312e.png)

**Comment by neurocean** [comment]
@ellbristow did you solve this?

**Comment by ellbristow** [comment]
> @ellbristow did you solve this?

The only way we could get round it was paginating the request and collating the results. It's a limitation of the Xero API at source, not the PyXero library, using the all request doesn't provide the line info
