### ISSUE TITLE
invalid grant

### ISSUE THREAD

**Issue by yonatan-payem** [freakboy3742/pyxero#296]
as shown in the Django example we use:
```
if credentials.expired():
    credentials.refresh()
```
but this throws `invalid grant`

**Comment by DBa19** [comment]
This error has suddenly appeared for me too, while previously it was working correctly (no changes made).

**Comment by marji** [comment]
@yonatan-payem  and @DBa19 this problem rings a bell, maybe this will help you. When I was learning how to use pyxero, experimenting with the example, I got stuck on the same problem.
In my case - I was not using the same scope with OAuth2Credentials() after the token got refreshed.

This code below works for me - note I use the same "my_scope" for both OAuth2Credentials() calls:

```
from xero.constants import XeroScopes
my_scope = [XeroScopes.OPENID,
            XeroScopes.OFFLINE_ACCESS,
            XeroScopes.ACCOUNTING_CONTACTS_READ,
            XeroScopes.ACCOUNTING_REPORTS_READ,
            XeroScopes.ACCOUNTING_TRANSACTIONS_READ]

token = my_function_to_load_token_from_storage()

credentials = OAuth2Credentials(client_id, client_secret, scope=my_scope, token=token)

if credentials.expired():
    print('Expired credentials, calling credentials.refresh()')
    credentials.refresh()
    new_token = credentials.token
    credentials = OAuth2Credentials(client_id, client_secret, scope=my_scope, token=new_token)

    # as token got updated, it needs to be saved (to be used when this program restarts):
    my_function_to_save_token_to_storage(new_token)

credentials.set_default_tenant()
...
...
```

**Comment by DBa19** [comment]
@marji Doubt the issue is credentials as I am using the default credentials only. Additionally, refreshing worked fine in my case for a few days, however now all of a sudden it stopped working.

Thanks

**Comment by schinckel** [comment]
I received this intermittently, it is generally when the scope has changed between the authorisation and the refresh request. In my case, it had not actually changed, but was an artefact from a migration of the 1.0 token to a 2.0 token. I was unable to reproduce it reliably though.
