### ISSUE TITLE
XeroRateLimitExceeded and HTTP response status code 429

### ISSUE THREAD

**Issue by zedtools** [freakboy3742/pyxero#297]
I switched to using OAuth2 recently, and it seems that the Xero API is returning a HTTP status code of 429 when the rate limit is exceeded. Previously this was 503.

This 429 response status code is documented here:

https://developer.xero.com/documentation/oauth2/limits

I noticed the pyxero code checks for 503 but not 429. The result is that a XeroExceptionUnknown is raised, which is misleading. The code should raise a XeroRateLimitExceeded if 429 is returned.

**Comment by SergeNasr** [comment]
Any updates on this issue?

**Comment by Sticky-Bits** [comment]
I'm guessing people are just switching to https://github.com/XeroAPI/xero-python

**Comment by timrichardson** [comment]
This issue can be closed now

**Comment by freakboy3742** [comment]
Resolved by #314
