### ISSUE TITLE
pypi version severely outdated

### ISSUE THREAD

**Issue by evrimoztamur** [freakboy3742/pyxero#342]
It looks like the pypi package is 0.9.3, which was released in 2021!

It doesn't have features such as the `PaymentManager` (and it was a frustrating journey finding out).

Any plans on updating the package?

**Comment by freakboy3742** [comment]
We're definitely overdue for a release. I need to find some time this to review a couple of outstanding PRs (#337, #341); once those have landed, I can cut a new release.

If you've got any feedback on those open PRs (even if that is "works for me"), that will likely speed up the review process.

**Comment by freakboy3742** [comment]
I've just published v0.9.4. Let us know if you have any issues.
