### ISSUE TITLE
Lists of 1 item are sometimes transformed to singletons

### ISSUE THREAD

**Issue by nicois** [freakboy3742/pyxero#51]
Using the demo company and interactive API, when I pull invoice details for 86d6e00f-ef56-49f7-9a54-796ccd5ca057 (in JSON view), it contains:
"LineItems": [
        {
          "ItemCode": "PMD",
          "Description": "Project Management for restructure - onsite daily rate",
...

However, the object returned via pyxero using invoice.get(...) includes:
'LineItems': {'LineItem': {'AccountCode': '200', ...

I am not sure what happens with an invoice with more than one line item. The demo organisation does not contain such invoices. I am also not sure if this is the only occurance, or if other entries are also collapsed.
In any event, there should be a list of LineItem objects, rather than a single bare dict.

**Comment by aidanlister** [comment]
I noticed this starts manifesting in a BIG way in Python3 ... possibly our isinstance use. I'm going to try and move toward the JSON API.

**Comment by aidanlister** [comment]
Should be fixed in e5a9c8b2f69e1e8bd9ef4b0e4c84c4e694e05a37
