### ISSUE TITLE
SSL error using Google App Engine

### ISSUE THREAD

**Issue by avoorhees** [freakboy3742/pyxero#57]
I'm using Google App Engine (1.9.17) and I am receiving a SSL error as follows:

    TypeError: must be _socket.socket, not socket

I am import ssl in the yaml as follows:

    - name: ssl
      version: latest

The same issue has been resolved for the Stripe API. [Link](https://github.com/stripe/stripe-python/pull/87/files)

Note: This does not happen when deployed but it happens when using the dev server.

Any chance something like this could happen with PyXero? Anyone know a workaround?

**Comment by aidanlister** [comment]
I'm guessing Google App Engine have fixed this by now.
