### ISSUE TITLE
Unable to Assign tracking codes to line items when creating invoice

### ISSUE THREAD

**Issue by madteckhead** [freakboy3742/pyxero#58]
These both fail to work. I was thwarted by https://github.com/freakboy3742/pyxero/issues/16, but now get the codes returned. Posting them to invoices seems to fail however. 
'''
items.append({
                'Description': description,
                'Quantity': '1.0',
                'UnitAmount': price,
                'AccountCode': '200',
                # 'DiscountRate': '0',
                'Tracking': {'TrackingCategory': {'TrackingCategoryID':'xxxxxx-6beb-4f36-a511-0d45f22c107e', 'Name': 'HH - Job', 'TrackingOptionID': 'xxxxxx-7814-4e74-a7cb-ed85f5e857a6'}},
                'TaxType': '%s' % tax_type,
            })
'''

and

'''
items.append({
            'Description': description,
            'Quantity': '1.0',
            'UnitAmount': price,
            'AccountCode': '200',
            # 'DiscountRate': '0',
            # 'Tracking': '200',
            'Tracking': {'TrackingCategory': {'TrackingCategoryID':'xxxxxx-6beb-4f36-a511-0d45f22c107e', 'Name': 'HH - Job', 'Option': 'The Big Client App},},
            'TaxType': '%s' % TAX_TYPE,
'''

**Comment by avoorhees** [comment]
This is how I create invoice with tracking categories


    line_items.append({"AccountCode": account_code,
                            "Reference": reference,
                            "Description": description,
                            "Quantity": quant,,
                            "UnitAmount": sale_price,
                            "Tracking": ({"TrackingCategory":{"Name":"TC2","Option":"Option1"}}, 
                            {"TrackingCategory":{"Name":"TC1", "Option":"Option2"}})
                       })

**Comment by madteckhead** [comment]
I confirm that works for me. Thanks
