### ISSUE TITLE
Files API

### ISSUE THREAD

**Issue by MJMortimer** [freakboy3742/pyxero#61]
I am looking at adding support for the recently released FIles API.

The Files API is a fair bit different to how the Accounting API has worked in the past. For example the Files API is more RESTful. If you were to update and existing folder for example the url would be a POST on  ..../Folders/{FolderID}. The Files API also uses the correct HTTP methods for creating (POST) and updating (PUT) so requests to the Files API are the opposite to what is implemented for the accounting endpoints in the wrapper. It is also JSON by default and much more JSON friendly and the current manager.py handles everything as XML.
All in all a lot of the files stuff would contradict with what is currently in manager.py. 

How would you suggest I go about adding the Files functionality? Would it be best if the manager.py was left for the 'accounting' aspects of the API and I created another class like a FilesManager.py for access to the Files API? Or something else?

**Comment by aidanlister** [comment]
Merged PR.
