### ISSUE TITLE
Payroll API

### ISSUE THREAD

**Issue by schinckel** [freakboy3742/pyxero#7]
The payroll API uses a different endpoint: instead of https://api.xero.com/api.xro/2.0, it uses https://api.xero.com/payroll.xro/1.0

Should I create a XeroPayroll class that is basically the same as the Xero class, that uses that endpoint instead? Do you think that is the best way to do that?

**Comment by MJMortimer** [comment]
@gavinhodge Have you made any more progress on this? Xero have released an API for Files and it uses a different url the same way payroll does. I am interested in seeing how you were going to have it work like 'Xero.Payroll.Timesheets.all()' so I can do the similar thing with 'Xero.Files.Folders' etc

**Comment by gavinhodge** [comment]
@MJMortimer I'm running a fork in production that has this change and can confirm that it seems to be a good way to structure the API. My branch isn't really in a good state to merge back here so I'd have to make the changes again from scratch.

**Comment by MJMortimer** [comment]
@gavinhodge Are you able to show me how you got that structure? So I have somewhere to start?

**Comment by gavinhodge** [comment]
Sure thing. My api.py looks something like this:

```python
from .manager import Manager


class Xero(object):
    """An ORM-like interface to the Xero API"""

    OBJECT_LIST = (u'Contacts', u'Accounts', u'CreditNotes',
                   u'Currencies', u'Invoices', u'Journals', u'Organisations',
                   u'Payments', u'Reports', u'TaxRates',
                   u'TrackingCategories', u'ManualJournals')

    def __init__(self, credentials):
        # Iterate through the list of objects we support, for
        # each of them create an attribute on our self that is
        # the lowercase name of the object and attach it to an
        # instance of a Manager object to operate on it
        for name in self.OBJECT_LIST:
            setattr(self, name.lower(), Manager(name, credentials.oauth, 'api'))

        self.payroll = Payroll(credentials)

class Payroll(object):
    """An ORM-like interface to the Xero Payroll API"""

    OBJECT_LIST = (u'Employees', u'Timesheets', u'PayItems')

    def __init__(self, credentials):
        for name in self.OBJECT_LIST:
            setattr(self, name.lower(), Manager(name, credentials.oauth, 'payroll'))
```

**Comment by MJMortimer** [comment]
@gavinhodge Thank you. I suspected it would be similar to that. Just wanted to make sure so we could keep a common theme

**Comment by aidanlister** [comment]
I merged some of this in, 59cc9ed, be great if someone picks it up!

**Comment by MattHealy** [comment]
Hi all,

I'm looking to pick up this library to replace the current PHP implementation I have in production. I've extended the work from 59cc9ed to cover the scenarios I need for my implementation. I've opened pull request #113 for these changes.

**Comment by aidanlister** [comment]
@MattHealy's PR has been merged in, hooray.
