### ISSUE TITLE
Case insensitive search

### ISSUE THREAD

**Issue by jacobg** [freakboy3742/pyxero#71]
According to this support thread:
   https://community.xero.com/developer/question/26871
you can do a case insensitive search such as:
   GET /api.xro/2.0/Invoices?where=Contact.Name.ToLower().Contains("abc")

Please support this in pyxero

**Comment by jacobg** [comment]
I hacked around it by doing this:

```python
def _search_contact_name(xero, name):

    def _filter(*args, **kwargs):
        uri, params, method, body, headers, singleobject = xero.contacts._filter(*args, **kwargs)
        params = {'where': 'Name.ToLower()=="%s"' % name.lower()}
        return uri, params, method, body, headers, singleobject

    return xero.contacts._get_data(_filter)()
```

Perhaps there could be a official solution which offers direct access to the where parameter.

**Comment by jacobg** [comment]
I just saw there's a long standing pull request on this waiting to be accepted by the "powers that be":

https://github.com/freakboy3742/pyxero/pull/54

**Comment by aidanlister** [comment]
I support a .raw() method if you want to provide a patch

**Comment by jacobg** [comment]
Would it look like this?

```python
    def _raw(self, params, headers=None):
        uri = '/'.join([self.base_url, self.name])
        return uri, params, 'get', None, headers, False
```

**Comment by aidanlister** [comment]
I would expect the userland syntax to be .filter(raw='xxx') or .rawfilter() maybe

**Comment by jacobg** [comment]
You mean to enhance the existing filter? What about just allowing a 'where' argument to be added to filter to override generating inside the filter from the other kwargs?

**Comment by aidanlister** [comment]
Yeah I was thinking it could be used to supplement, I think if we add it to the end at least the behaviour is consistent and can be documented.

**Comment by aidanlister** [comment]
This is now implemented via filter(raw='Contact.Name.ToLower().Contains("abc")')
