### ISSUE TITLE
Exception on "XeroBadRequest" exception class in exceptions.py

### ISSUE THREAD

**Issue by supermarcos** [freakboy3742/pyxero#78]
Hello, I am using your library and I realised than on the class "XeroBadRequest" in exceptions.py, they may be something extreme that could cause exceptions...

To test it, do this: create an invoice (for instance an invoice) with a fake ContactID that you're sure is not on your database. Then, by the line 23, when the loop is trying to pull the error messages out, it will fail since in certain situations the Xero API is not responding "Elements" on data so it is not possible to use "data['elements']" because it doesn't exist.

I changed the source of the __init__ function to this (just in case it is valid and you want to use it in your code):
```python
self.errors = [err['Message']
    for elem in data.get('Elements', [])
    for err in elem.get('ValidationErrors', [])
] or [data['Message']]
```

Cheers!

**Comment by direvus** [comment]
I ran into this too.  Thanks @supermarcos for posting that workaround.

**Comment by seddonym** [comment]
Yes I ran into this one too.

**Comment by direvus** [comment]
@seddonym Looks like development has stalled on this repo for the time being.  You could always run a checkout of my branch which includes PR #93, that's what I've been doing.  Or patch that commit into your copy by hand.

**Comment by seddonym** [comment]
Thanks direvus, I'll take a look!

**Comment by aidanlister** [comment]
Aye I'm out of time :(
