### ISSUE TITLE
Response when something fails but not everything

### ISSUE THREAD

**Issue by supermarcos** [freakboy3742/pyxero#79]
Hello!

I have a case where I am posting invoices (a bunch of them) and some of them are right and they will be created, but one or more may be wrong... I'd like to have the possibility to get a response from the API that helps me to identify what's OK pushed and what's not... At the moment, if there is just one wrong invoice within x right ones, the library will throw an exception and it will give me a lot of information about the wrong one, but nothing about the right ones. If everything goes well, I should get the invoiceId along more information so I can identify what is well pushed and put the id on my side, but if there is something wrong... I can't because of the design of the exception... not sure if that's how Xero in itself responses the whole request, but if is in that way, something is not right there...

Can someone tell me if I am using it right or should I get more information from another way?
I am using just 
```python
try:
  res = xero.invoices.put([array_invoices]) 
except XeroException as e:
  res = e.__dict__
```
and then I read res... if everything is OK, res will have nice information about the new invoices created, if something goes wrong, it will throw an exception, reading the data in that exception I can figure out which part is wrong, but I can't know anything else about the ones that went OK and have been created on the Xero database propertly so I lost my track to them.

Thank you very much in advance!

**Comment by schinckel** [comment]
It's possible that this information is just not available from the API: I know there are limitations with attempting to get this information. I've reported this as an issue to Xero developer support, but haven't had a response suggesting it will be fixed in the short term.

In our case, we needed to drop down to individual requests per item (putting us at risk of hitting API limits), because we couldn't even see which item was incorrect.

**Comment by aidanlister** [comment]
Have you had a chance to test the new 1.7-alpha @schinckel ?

**Comment by supermarcos** [comment]
Hi @schinckel, thank you for your answer!
Yes, exactly, that's my issue too... or I push all the items one by one or I will lost the information from the ones that went well if there is just one wrong...
That's pretty sad. Untill now I was quite happy about the Xero API... There is a high risk of hitting the API limits doing it one by one.

Hi @aidanlister, the 1.7-alpha revision has something new about that part? How can I test it?
Thank you!

**Comment by supermarcos** [comment]
Hi, guys, as @schinckel said, it seems to be a problem deeper, on the Xero RestFul API in itself, go to this tool they have:
https://app.xero.com/Preview/invoices/PUT

And try to put a couple of invoices, one right and one wrong (for instance, in the wrong one, change the contact name node by "ContactNumber" with whatever wrong number, it will fail), they you will see that the response from their API is just talking about the wrong part, but nothing about the well built one even though the good one will be created correctly on the database.

Oooups... that seems like a bug to me... I already asked on their community forums about it on a thread someone asked something similar.

Has someone solved this issue in a different way or there is no workaround apart of the @schinckel suggestion?

Thank you!

**Comment by schinckel** [comment]
@aidanlister I'm not actually using pyxero: the code I have diverged quite some time ago, and I'm not currently permitted to release it back.

**Comment by supermarcos** [comment]
Hey, everyone again!

I found a solution for this without hammering the API one by one. Actually is on their API documents but I missed it. The key is using summarize_errors = False. In the manager.py document on this wrapper is set by default to True, but it has to set to False so the errors will be right described for each one of the invoices (or whatever element) you put or save, so that you have full information about what happened to the last batch post and do something in consecuence.

I hope this may help someone with the same issue. Remember to change summarize_errors to False in manager.py documment.

Thanks a lot.
I will close this issue.

**Comment by schinckel** [comment]
Ah, I assumed you were already using that: with some of the payroll API calls, summarizeErrors doesn't actually work properly.

**Comment by supermarcos** [comment]
I didn't realize before since these are my first steps using Xero and its API... I don't even need make use of the payroll API otherwise probably I would have found it as you say.
Anyway, as my mother used to say: "Well it is if well it ends", hehe

Thanks, mate!
