### ISSUE TITLE
Reduce verbosity in collections.

### ISSUE THREAD

**Issue by schinckel** [freakboy3742/pyxero#8]
The Xero API is quite verbose (and generally consistent), where it returns structures that look like:

    <Foos>
        <Foo>
            <Bar>baz</Bar>
            <Qux>quux</Qux>
        </Foo>
        <Foo>
            <Bar>wibble</Bar>
            <Qux>wobble</Qux>
        </Foo>
    </Foos>

Currently, this generates a data structure that looks like:

    {
        'Foos': [
            {'Foo': {'Bar':'baz','Qux':'quux'}},
            {'Foo': {'Bar':'wibble','Qux':'wobble'}},
        ]
    }

To me, there is no need for the wrapper object 'Foo'. I would propose that it generates an output of:

    {
        'Foos': [
            {'Bar':'baz','Qux':'quux'},
            {'Bar':'wibble','Qux':'wobble'},
        ]
    }

Is there a reason I am not thinking of that the previous one is preferable?

**Comment by aidanlister** [comment]
We're using JSON now, hooray.
