### ISSUE TITLE
How to do an "OR" filter?

### ISSUE THREAD

**Issue by supermarcos** [freakboy3742/pyxero#82]
Hello, there!

I'm trying to write a query of contacts where the Account number could be one of anyone from a list... how can I do that with this pyxero library?

Thank you!

**Comment by aidanlister** [comment]
Hey you can use raw filtering, e.g:

```raw='Name.ToLower()=="test contact" OR xxx'```

See http://developer.xero.com/documentation/api/

**Comment by supermarcos** [comment]
Oh! That's great! Sweet! Thank you, mate!
