### ISSUE TITLE
Partner credentials permission denied from Google AppEngine

### ISSUE THREAD

**Issue by supermarcos** [freakboy3742/pyxero#87]
Hello everyone,

Has anyone had issues trying to connect to Xero using Partner Certificates from Google AppEngine?

I allways get "permission denied", it is only from Google AppEngine, I've tried in other environment and it worked fine, but it seems that Google AppEngine take control of the url request at the last point and alters it adding something that Xero doesn't expect so they reject the connection attempt.

I've suggested to use sockets instead of a normal request, but even in that way I'm experiencing the same issue. I wonder if this last case has something to do with the certificate. There are aparently two ways of sending the certificate: one is as a tuple of the paths to the pair of pem files and another it seems to be possible to send a string that, I assume, it must be the content of both pem bundled (but I'm not sure...).
So, my questions are:
One: Has anyone got pyXero and Partnership program to Xero working on Google AppEngine? If so, how? What am I missing?
Two: what should be the content of the cert variable in "PartnerCredentials" class constructor if I chose to send the content of the client certificate instead of the tuple of the pair of pem files paths?

Thank you very much, I'd appreciate any kind of help.

**Comment by aidanlister** [comment]
We don't support Google App Engine ... but I'll leave this open in case
anyone has an idea.

**Comment by supermarcos** [comment]
Hi, @aidanlister 
That's because you know there are some issues or just because GAE hasn't been implemented?
Thank you, anyway

**Comment by aidanlister** [comment]
Yes there are issues with SSL because GAE doesn't have true Python versions
of things. Search previous issues for this package, or Python requests
package

**Comment by supermarcos** [comment]
Thanks, @aidanlister 
That makes sense... hopefully someone found a workaround.
Thank you for your help anyway.
